apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot
    app.kubernetes.io/part-of: appstudio
  name: java-springboot
  namespace: shebert
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-springboot
status:
  loadBalancer: {}
